Jjy kakao notice
LINE-NOW/LINENOW-Server pull request #46
Opened 2024-09-27 15:38 UTC by jiyoon607

# 🔥 Pull requests
첫 Pr.. 잘부탁 드립니다..!

## 👷 작업한 내용
카카오 API를 이용하여 로그인, 회원가입을 구현했습니다. 클라이언트에서 카카오에 인가 코드 발급 요청을 보내면 redirect URI를 통해 서버에 접근하여 로그인/회원가입이 되며, access 토큰과 refresh 토근을 부여합니다. 응답 구조도 맞추어보았습니다!

## 🚨 참고 사항
현재 로그인/회원가입 시, response로 access 토큰과 refresh 토큰을 반환하지만, 쿠키에 저장이 되지는 않는 문제가 있습니다.

## 📸 스크린샷

### 카카오 로그인 성공
![카카오로그인성공](https://github.com/user-attachments/assets/dce8e9a6-340f-4695-ac68-a2c287978492)

### 카카오 회원가입 성공
![회원가입 성공](https://github.com/user-attachments/assets/15be7ac8-1ff5-4c48-bb86-2d5822550eaf)

### 카카오 인가 코드 오류
![카카오토큰오류](https://github.com/user-attachments/assets/36b9c928-a8db-4ac7-955a-7b7cd5b2a10e)

## 🖥️ 주요 코드 설명
- redirect URI의 콜백함수 코드입니다. 인가 코드를 보내서 access token을 발급 받고 access token을 보내서 프로필 정보를 받습니다. access토큰과 refresh토큰을 발급하여 response로 제공합니다.
```python
    client_id = settings.KAKAO_CLIENT_ID
    code = request.GET.get("code")

    # code로 access token 요청
    token_req = requests.get(f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={KAKAO_CALLBACK_URI}&code={code}")
    token_req_json = token_req.json()

    error = token_req_json.get("error", None)
    
    if error is not None:
        raise InvalidToken("The access token from Kakao was invalid.")

    kakao_access_token = token_req_json.get("access_token")
    
    # 프로필 정보 요청
    profile_request = requests.get("https://kapi.kakao.com/v2/user/me", headers={"Authorization": f"Bearer {kakao_access_token}"})
    profile_json = profile_request.json()
    
    kakao_account = profile_json.get('kakao_account')
    email = kakao_account.get('email', None)
    
    try:
        user = User.objects.get(email=email)
        
        # 기존에 kakao로 가입된 유저
        data = {"access_token": kakao_access_token, "code": code}
        accept = requests.post(f"{BACK_BASE_URL}api/v1/accounts/kakao/login/finish/", data=data)
        accept_status = accept.status_code
        
        if accept_status != 200:
            return InvalidToken("Login Failed.")

        accept_json = accept.json()

        # refresh_token을 headers 문자열에서 추출
        refresh_token = accept.cookies.get('refresh_token')
        if not refresh_token:
            raise InvalidToken("Failed to retrieve refresh token.")
        
        access_token = accept_json['access']
        
        data = {
            "access_token": access_token,
            "refresh_token": refresh_token
        }

        return custom_response(data=data, message="Login successful.", code=status.HTTP_200_OK)
```

- 토큰 오류를 응답하는 클래스를 작성해보았습니다.. 이렇게 사용하는 것이 맞는지 확인 부탁드립니다..! 문제가 있다면 수정하겠습니다 !
```python
class InvalidToken(APIException):
    status_code = 401
    default_detail = 'The token was invalid.'
    default_code = 'invalid_token' 
```
## ✅ Check List
- [x] Merge 대상 브랜치가 올바른가?
- [x] 최종 코드가 에러 없이 잘 동작하는가?

## 📟 관련 이슈
- Resolved: #2

2024-09-28 06:06 UTC, JongbeomLee623 requested changes
댓글 확인 후 답변 바랍니다!

2024-09-28 06:06 UTC, JongbeomLee623 commented on accounts/urls.py
dj_rest_auth 통한 로그인은 배포 전에 없애는 것이 좋을 것 같습니다.

2024-09-28 06:06 UTC, JongbeomLee623 commented on accounts/views.py
> +        # 기존에 가입된 유저가 없으면 새로 가입
이 부분에서 가입된 유저가 없으면 새로 가입한다고 작성하였는데, 회원가입하는로직이 없는 것 같은데 맞을까요? 아니면 다른 곳에서 한다던가,,? 있을까여,,?

2024-09-29 06:10 UTC, jiyoon607 commented
수정했습니다 ! 확인 부탁드립니다 !

2024-09-29 12:49 UTC, dudtlstm commented
확인했습니다. 수고 많으셨습니다 !

2024-09-30 04:08 UTC, merged